<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Agendar Consulta</title>
    <link rel="stylesheet" href="../background.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
</head>

<style>
    {
        background-image: url("background.jpg");
        background-repeat: no-repeat;
    }

    ;
</style>

<body>
    <form action="/agendar_consulta/" method="post">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="../gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/login/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="inicio.html">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Agendar consulta</li>
                    </ol>
                </nav>
            </div>
            <div class="m-5 text-white">
                <h1>Agende sua consulta:</h1>
            </div>
            <form action="agendar_consulta" method="post">
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group date" id="datetimepicker4" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4" name="agenda">
                            <div class="input-group-append" data-target="#datetimepicker4" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-5">
                    <div class="row">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupSelect01">Confirmar nutricionista:</label>
                            </div>
                            <select class="custom-select" id="inputGroupSelect01" name="nomeNutri">
                                <option selected>Escolha...</option>
                                <option value="Rosana Tamares">Rosana Tamares</option>
                                <option value="Rafael Soares">Rafael Soares</option>
                                <option value="Cláudia Mendes">Cláudia Mendes</option>
                                <option value="Arnaldo César">Arnaldo César</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Preço</span>
                        </div>
                        <select name="preco">
                        <option>Preço</option>
                        <option>250</option>
                        <option>500</option>
                        <option>750</option>
                    </div>
                </div>
            </form>
            <div class="text-center m-3">
                <input type="submit">
            </div>
        </div>
        </div>
    </form>
</body>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
<script type="text/javascript">
    $(function() {
        $('#datetimepicker4').datetimepicker({
            format: 'L'
        });
    });
</script>

</html>