<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Assistência</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/ajuda/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/login/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/inicio/">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Ajuda</li>
                    </ol>
                </nav>
            </div>
            <div class="m-5">
                <h1>Problemas com...</h1>
                <div class="mb-5">
                    <a class="d-block m-3" href="#">Esqueceu sua senha?</a>
                    <a class="d-block m-3" href="#">Problemas na autênticação?</a>
                    <a class="d-block m-3" href="#">Dificuldade no pagamento?</a>
                    <a class="d-block m-3" href="#">Atraso no pagamento?</a>
                </div>
            </div>
        </div>
        <footer class="fixed-bottom p-4 bg-dark border rounded-top">
            <p class="text-white">Contatos:</p>
            <p class="text-white">WhatsApp: <a href="">(47)9565-4723</a></p>
            <p class="text-white">Instagram: <a href="">@acadmiaoficial</a></p>
            <p class="text-white">E-mail: <a href="">acadmiadoborel@gmail.com</a></p>
        </footer>
    </form>
</body>

</html>