<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Criar Conta</title>
    <link rel="stylesheet" href="../criar_conta.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="background.css">
</head>

<body>
    <?php
    if (isset($action) && $action == "user-already-exists") {
        echo '
        <div class="alert alert-danger mt-5" role="alert">
            <h4 class="alert-heading">Erro: Nome de usuário já está em uso!</h4>
            <p class="text-center">Esse nome já foi utilizado por outro usuário, tente outro.</p>
            <hr>
            <p class="mb-0 text-center">Aviso: digite novamente sua senha.</p>
        </div>
        ';
    } else if (isset($action) && $action == "blank-fields") {
        echo '
        <div class="alert alert-danger mt-5" role="alert">
            <h4 class="alert-heading">Erro: Preencha todos os campos obrigatórios!</h4>
            <p class="text-center">Verifique se algum campo não foi preenchido.</p>
            <hr>
            <p class="mb-0 text-center">Aviso: digite novamente sua senha.</p>
        </div>
        ';
    } else if (isset($action) && $action == "email-not-valid") {
        echo '
        <div class="alert alert-danger mt-5" role="alert">
            <h4 class="alert-heading">Erro: O email não é válido!</h4>
            <p class="text-center">Verifique se o email foi digitado corretamente.</p>
            <hr>
            <p class="mb-0 text-center">Aviso: digite novamente sua senha.</p>
        </div>
        ';
    }
    ?>
    <form action="/criar_conta/" method="post">
        <div class="container">
            <div class="text-center m-5">
                <h1>Crie sua conta</h1>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nome completo</span>
                        </div>
                        <input type="text" name="nome" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">E-mail</span>
                        </div>
                        <input type="email" name="email" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Senha</span>
                        </div>
                        <input type="password" name="senha" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Confirmar senha</span>
                        </div>
                        <input type="password" name="confirmarSenha" class="form-control">
                    </div>
                </div>
                <?php
                if (isset($action) && $action == "passwords-not-equal") {
                    echo '<h5 class="alert alert-danger my-3">Erro: As senhas não batem!</h5>';
                }
                ?>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Cidade</span>
                        </div>
                        <input type="text" name="cidade" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">CEP</span>
                        </div>
                        <input type="number" name="cep" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Nº da casa</span>
                        </div>
                        <input type="number" name="numeroCasa" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Complemento</span>
                        </div>
                        <input type="text" name="complemento" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Idade</span>
                        </div>
                        <input type="number" name="idade" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text label" id="basic-addon1">Sexo</span>
                            <span class="input-group-text ml-1 label" id="basic-addon1">Masculino</span>
                            <div class="input-group-text radio">
                                <input type="radio" name="sexo" value="Masculino">
                            </div>
                            <span class="input-group-text ml-1 label" id="basic-addon1">Feminino</span>
                            <div class="input-group-text radio">
                                <input type="radio" name="sexo" value="Feminino">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Mensalidade</span>
                        </div>
                        <select class="custom-select" name="mensalidade">
                            <option value="">Escolha...</option>
                            <option value="250,00">R$250,00</option>
                            <option value="500,00">R$500,00</option>
                            <option value="750,00">R$750,00</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Enviar" class="btn btn-secondary">
            </div>
        </div>
    </form>
</body>

</html>