<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Criar Conta</title>
    <link rel="stylesheet" href="../criar_conta.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="background.css">
</head>

<body>
    <form action="/criar_conta/" method="post">
        <div class="container">
            <div class="text-center m-5">
                <h1>Crie sua conta</h1>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Nome completo</span>
                        </div>
                        <input type="text" name="nome" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">E-mail</span>
                        </div>
                        <input type="email" name="email" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Senha</span>
                        </div>
                        <input type="password" name="senha" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Cidade</span>
                        </div>
                        <input type="text" name="cidade" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">CEP</span>
                        </div>
                        <input type="number" name="cep" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Nº da casa</span>
                        </div>
                        <input type="number" name="numeroCasa" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Complemento</span>
                        </div>
                        <input type="text" name="complemento" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Idade</span>
                        </div>
                        <input type="number" name="idade" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text label">Sexo</span>
                            <span class="input-group-text ml-1 label">Masculino</span>
                            <div class="input-group-text radio">
                                <input type="radio" name="sexo" value="Masculino" required>
                            </div>
                            <span class="input-group-text ml-1 label">Feminino</span>
                            <div class="input-group-text radio">
                                <input type="radio" name="sexo" value="Feminino" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Mensalidade</span>
                        </div>
                        <select class="custom-select" name="mensalidade" required>
                            <option value="">Escolha...</option>
                            <option value="250,00">R$250,00</option>
                            <option value="500,00">R$500,00</option>
                            <option value="750,00">R$750,00</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="text-center mb-3">
                <input type="submit" value="Enviar" class="btn btn-secondary">
            </div>
        </div>
    </form>
</body>

</html>