<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Financeiro</title>
    <link rel="stylesheet" href="../background.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/financeiro/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="../gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/sair/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/inicio/">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Financeiro </li>
                    </ol>
                </nav>
            </div>
            <div class="col-12 text-white">
                <div class="row">
                    <div class="col-md-2 border border-primary text-center">
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
                        <input type="file" id="imgload">
                        <img src="#" id="imgshow">
                        <div class="row">
                            <?php echo $_SESSION['login']['nome']; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 mt-4">
                <div class="row">
                    <div class="card col-8 col-md-3 offset-md-3 mr-1 border rounded border-black">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Mensalidade</li>
                            <li class="list-group-item">Consulta com Nutricionista</li>
                            <li class="list-group-item">Suplementos</li>
                            <li class="list-group-item">Total:</li>
                        </ul>
                    </div>
                    <div class="card col-4 col-md-3 ml-1 border rounded border-black">
                        <?php
                        echo '<ul class="list-group list-group-flush">';
                        echo    '<li class="list-group-item">R$' . $_SESSION['login']['mensalidade'] . '</li>';
                        echo    '<li class="list-group-item">R$' . $_SESSION['precoConsulta'] . '</li>';
                        echo    '<li class="list-group-item">R$' . $totalSoma . '</li>';
                        echo    '<li class="list-group-item">R$' . $_SESSION['produto']['valor_total'] . '</li>';
                        echo '</ul>';
                        ?>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <button type="submit" class="ml-2 btn btn-light text-center mt-5 mb-5">Pagar</button>
                </div>
            </div>
        </div>
    </form>
</body>
<script type="text/javascript" src="../imgload.js"></script>

</html>