<!-- <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>

<body>
    <h1>cadastro</h1>

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">nome</th>
                <th scope="col">email</th>
                <th scope="col">senha</th>
                <th scope="col">telefone</th>
                <th scope="col">mensalidade</th>
                
            </tr>
            </tbody>
    </table>
    <?php
    foreach ($cadastro as $key => $value) {
        echo "<tr>";
        echo "<td>" . $value['idcadastro'] . " - " . "</td>";
        echo "<td>" . $value['nome'] ." " . "</td>";
        echo "<td>" . $value['email'] ." " . "</td>";
        echo "<td>" . $value['senha'] ." " . "</td>";
        echo "<td>" . $value['telefone'] ." " . "</td>";
        echo "<td>" . $value['mensalidade'] ." " . "</td>";
        echo "<tr>";
    }
    ?>
</body>

</html> -->

<?php
            foreach ($textos as $key => $texto) {
                echo '<div class="col-12">';
                echo ' <div class="row">';
                echo ' <div class="col-sm">';
                echo '<a href="/ajuda/" class="card card-link mb-5">';
                echo '      <div class="card-body text-dark">';
                echo '<h5 class="card-title">Ajuda</h5>';
                echo '<p class="card-text">'. $texto['texto_ajuda'] . '</p>';
                echo '</div>';
                echo '</a>';
                echo '</div>';
            }
            /*
                <div class="col-sm">
                    <a href="/desafio/" class="card card-link mb-5">
                        <div class="card-body text-dark">
                            <h5 class="card-title">Desafios</h5>
                            <p class="card-text"><?= $textos['texto_desafios'] ?></p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-sm">
                    <a href="/financeiro/" class="card card-link mb-5">
                        <div class="card-body text-dark">
                            <h5 class="card-title">Financeiro</h5>
                            <p class="card-text"><?= $textos['texto_financeiro'] ?></p>
                        </div>
                    </a>
                </div>
                <div class="col-sm">
                    <a href="/meta/" class="card card-link mb-5">
                        <div class="card-body text-dark">
                            <h5 class="card-title">Metas</h5>
                            <p class="card-text"><?= $textos['texto_meta'] ?></p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-sm">
                    <a href="/suplemento/" class="card card-link mb-5">
                        <div class="card-body text-dark">
                            <h5 class="card-title">Suplementos</h5>
                            <p class="card-text"><?= $textos['texto_suplemento'] ?></p>
                        </div>
                    </a>
                </div>
                <div class="col-sm">
                    <a href="/ajuda/" class="card card-link mb-5">
                        <div class="card-body text-dark">
                            <h5 class="card-title">Consultas</h5>
                            <p class="card-text"<?= $textos['texto_consulta'] ?></p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
*/
            ?>