 <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>

<body>
    <h1 class="m-5">Suplementos</h1>
    <div class="container text-white">
        <div class="m-5">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="inicio.html">Início</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Suplementos</li>
                </ol>
            </nav>
        </div>
        <div class="col-12 text-center">
            <div class="row">
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey1.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey2.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey3.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
            </div>
            <div class="row">
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey4.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey5.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
                <a href="suplemento_selec.html" class="col-sm p-5 mb-3 border border-secondary rounded card-link">
                    <img src="img/whey6.png" height="500px" width="500px" class="img-fluid" alt="">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </a>
            </div>
        </div>
    </div>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">nome</th>
                <th scope="col">quantidade</th>
            </tr>
            </tbody>
    </table>
    <?php
    foreach ($produto as $key => $value) {
        echo "<tr>";
        echo "<td>" . $value['idproduto'] . " - " . "</td>";
        echo "<td>" . $value['nomeProduto'] . " " . "</td>";
        echo "<td>" . $value['qntProduto'] . " " . "</td>";
        echo "<tr>";
    }
    ?>
</body>

</html> -->