<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Início</title>
    <link rel="stylesheet" href="../background.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/inicio/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="../gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/sair/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Início</li>
                    </ol>
                </nav>
            </div>
            <div class="m-5 text-white">
                <h1>Bem vindo, <?php echo $_SESSION['login']['nome']; ?>!</h1>
            </div>
            <?php
            foreach ($textos as $key => $texto) {
                echo '<div class="col-12">';
                    echo '<div class="row">';
                        echo '<div class="col-12">';
                            echo ' <div class="row">';
                                echo ' <div class="col-sm">';
                                    echo '<a href="/ajuda/" class="card card-link mb-5">';
                                        echo '<div class="card-body text-dark">';
                                            echo '<h5 class="card-title">' . $texto['titulo_ajuda'] . '</h5>';
                                            echo '<p class="card-text">' . $texto['texto_ajuda'] . '</p>';
                                        echo '</div>';
                                    echo '</a>';
                                echo '</div>';
                                echo '<div class="col-sm">';
                                    echo '<a href="/desafio/" class="card card-link mb-5">';
                                        echo '<div class="card-body text-dark">';
                                            echo '<h5 class="card-title">' . $texto['titulo_desafio'] . '</h5>';
                                            echo '<p class="card-text">' . $texto['texto_desafio'] . '</p>';
                                        echo '</div>';
                                    echo '</a>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    echo '<div class="col-12">';
                        echo '<div class="row">';
                            echo '<div class="col-sm">';
                                echo '<a href="/financeiro/" class="card card-link mb-5">';
                                    echo '<div class="card-body text-dark">';
                                        echo '<h5 class="card-title">' . $texto['titulo_financeiro'] . '</h5>';
                                        echo '<p class="card-text">' . $texto['texto_financeiro'] . '</p>';
                                    echo '</div>';
                                echo '</a>';
                            echo '</div>';
                            echo '<div class="col-sm">';
                                echo '<a href="/meta/" class="card card-link mb-5">';
                                    echo '<div class="card-body text-dark">';
                                        echo '<h5 class="card-title">' . $texto['titulo_meta'] . '</h5>';
                                        echo '<p class="card-text">' . $texto['texto_meta'] . '</p>';
                                    echo '</div>';
                                echo '</a>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                    echo '<div class="col-12">';
                        echo '<div class="row">';
                            echo '<div class="col-sm">';
                                echo '<a href="/suplemento/" class="card card-link mb-5">';
                                    echo '<div class="card-body text-dark">';
                                        echo '<h5 class="card-title">' . $texto['titulo_suplemento'] . '</h5>';
                                        echo '<p class="card-text">' . $texto['texto_suplemento'] . '</p>';
                                    echo '</div>';
                                echo '</a>';
                            echo '</div>';
                            echo '<div class="col-sm">';
                                echo '<a href="/agendar_consulta/" class="card card-link mb-5">';
                                    echo '<div class="card-body text-dark">';
                                        echo '<h5 class="card-title">' . $texto['titulo_consulta'] . '</h5>';
                                        echo '<p class="card-text">' . $texto['texto_consulta'] . '</p>';
                                    echo '</div>';
                                echo '</a>';
                            echo '</div>';
                        echo '</div>';
                    echo '</div>';
                echo '</div>';
            }
            ?>
    </form>
</body>

</html>