<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Início</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/inicio/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/login/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Início</li>
                    </ol>
                </nav>
            </div>
            <div class="m-5">
                <h1>Bem vindo, Usuário!</h1>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-sm">
                        <a href="/ajuda/" class="card card-link mb-5">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Ajuda</h5>
                                <p class="card-text">Aqui você pode contar com ajuda de nosso suporte técnico, além de ter
                                    acesso aos contatos da academia.</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm">
                        <a href="/desafio/" class="card card-link mb-5">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Desafios</h5>
                                <p class="card-text">Clique aqui para ver seus desafios propostos pelo seu personal trainer.
                                </p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-sm">
                        <a href="/financeiro/" class="card card-link mb-5">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Financeiro</h5>
                                <p class="card-text">Tenha visão total de seus gastos na academia, como: suplementos,
                                    boletos, etc.</p>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm">
                        <a href="/meta/" class="card card-link mb-5">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Metas</h5>
                                <p class="card-text">Clicando aqui, você poderá gerenciar suas metas, podendo editá-las ou
                                    criá-las.</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <a href="/suplemento/" class="card card-link mb-5">
                            <div class="card-body text-dark">
                                <h5 class="card-title">Suplementos</h5>
                                <p class="card-text">Confira os nossos suplementos com promoções e preços imperdíveis.</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>

</html>