<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>login</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <h1>Login</h1>
    <form action="/login/" method="post">

        <label for="email">E-mail</label>
        <input type="email" name="email" id="email">
        <br>
        <label for="senha">Senha</label>
        <input type="password" name="senha" id="senha">
        <br>
        <input type="submit" value="enviar">

    </form>

</body>

</html>