<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Meta</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../background.css">
</head>

<body>
    <form action="/meta/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/login/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/inicio/">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Metas</li>
                    </ol>
                </nav>
            </div>
            <div class="text-center m-5">
                <h1>Metas</h1>
            </div>
            <div class="col-12">
                <div class="row">
                    <div class="col-8 col-md-8 border border-secondary rounded float-left text-right">
                        <p>Perder 5Kg</p>
                        <p>Levantamento de peso: 5Kg</p>
                        <p>Correr 2Km na esteira</p>
                    </div>
                    <div class="col-4 col-md-4 float-left">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text rounded">
                                    <input type="checkbox" aria-label="Checkbox for following text input">
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text rounded">
                                    <input type="checkbox" aria-label="Checkbox for following text input">
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <div class="input-group-text rounded">
                                    <input type="checkbox" aria-label="Checkbox for following text input">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>

</html>