<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Meta</title>
    <link rel="stylesheet" href="../background.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/meta/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="../gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/sair/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/inicio/">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Metas</li>
                    </ol>
                </nav>
            </div>
            <div class="text-center m-5 text-white">
                <h1>Metas</h1>
            </div>
            <div class="col-12">
                <div class="row">
                    <?php
                    foreach ($descricoes as $key => $descricao) {
                        echo '<div class="col-12 mb-3 bg-white border border-secondary rounded float-left">';
                            echo '<div class="col-10 float-left">';
                                echo '<p class="my-auto">' . $descricao['descricaoMeta'] . '</p>';
                            echo '</div>';
                            echo '<div class="col-2 float-left">';
                                echo '<div class="input-group-text rounded">';
                                    echo '<input type="checkbox" class="mr-4" aria-label="Checkbox for following text input">';
                                    echo '<a href="">Editar</a>';
                                echo '</div>';
                            echo '</div>';
                        echo '</div>';
                    }
                    ?>
                </div>
                <!-- <div class="row">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">With textarea</span>
                        </div>
                        <textarea class="form-control" name="editarMeta" aria-label="With textarea"></textarea>
                    </div>
                </div> -->
            </div>
        </div>
    </form>
</body>

</html>