<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Suplemento</title>
    <link rel="stylesheet" href="../background.css">
    <link rel="shortcut icon" href="../gym.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/suplemento/" method="get">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand text-white" href="/inicio/"><img src="../gym.png" class="mr-3" width="30" height="30" alt="">Acadmia do Borel</a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/inicio/">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="/suplemento/">Suplementos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/financeiro/">Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/ajuda/">Ajuda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/desafio/">Desafios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/meta/">Metas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="/agendar_consulta/">Consultas</a>
                    </li>
                </div>
                <span class="navbar-text">
                    <a href="/login/">Sair</a>
                </span>
            </div>
        </nav>
        <div class="container">
            <div class="m-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/inicio/">Início</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Suplementos</li>
                    </ol>
                </nav>
            </div>
            <div class="text-center m-5 text-white">
                <h1>Suplementos</h1>
            </div>

        <?php 
        foreach($produtos as $produto){
            echo '<div class="col-4 text-center float-left">';
                echo '<div class="row ">';
                    echo '<a href='."/suplemento_selec/".$produto['idproduto'].' class=" col-10  suplemento text-warning flex-container aling-center p-5 m-4 border border-secondary rounded card-link">';
                    echo '<img src="' .$produto['endereçoIMG']. '" height="300px" width="200px" class="img-fluid">';
                    echo '<i class="fas fa-star"></i>';
                    echo '<i class="fas fa-star"></i>';
                    echo '<i class="fas fa-star"></i>';
                    echo '<i class="fas fa-star"></i>';
                    echo '<i class="fas fa-star"></i>';
                    echo '<br>';
                    echo '<div class="row">';
                    echo '<h3 class="text-dark">'.$produto['nomeProduto'].'</h3>';
                    echo '</div>';
                    echo '<div class="row">';
                    echo '<h2 class="text-dark">R$'.$produto['preco'].',00</h2>';
                    echo '</div>';
                    echo '<div>';
                    echo '<button type="button" class="btn btn-warning">Adicionar</button>';
                    echo '</div>';
                    echo '</a>';
                    echo '</div>';
                    echo '</div>';
        }
        ?>
            </div>
        </div>
    </form>
</body>

</html>